repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-    repo: local

     hooks:

      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: [--line-length=200, --target-version=py37]

      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        args: [
        "--ignore=E203,E501,W503,F401,FI10,FI11,FI12,FI13,FI14,FI15,FI16,FI17,FI58,PT013",
        # black
        # E203 whitespace before ':'
        # W503 line break before binary operator
        # flake8-future-import
        # FI10 future import "division" missing
        # FI11 future import "absolute_import" missing
        # FI12 future import "with_statement" missing
        # FI13 future import "print_function" missing
        # FI14 future import "unicode_literals" missing
        # FI15 future import "generator_stop" missing
        # FI16 future import "nested_scopes" missing
        # FI17 future import "generators" missing
        # FI58 future import "annotations" present
        # flake8-pytest-style
        # PT013 found incorrect import of pytest, use simple 'import pytest' instead
        "--max-line-length=110",
        "--per-file-ignores=tests/*.py:S101"
        # S101 Use of assert detected
        ]

      - id: isort
        name: isort
        entry: isort
        language: python
        args: ["--profile", "black", "--filter-files"]
        require_serial: false
        additional_dependencies: [ ]
        minimum_pre_commit_version: '0'

      - id: pyupgrade
        name: pyupgrade
        entry: pyupgrade
        language: system
        types: [ python ]
        args: [ --py37-plus ]
