# Generated by Django 4.2.2 on 2023-07-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mentorship", "0002_create_teacher_student_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="groups",
        ),
        migrations.AddField(
            model_name="group",
            name="student",
            field=models.ManyToManyField(blank=True, to="mentorship.student"),
        ),
        migrations.AddField(
            model_name="student",
            name="rating",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
