# Generated by Django 4.2.2 on 2023-07-31 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testing_system", "0001_create_course_model"),
        ("mentorship", "0003_change_teacher_student_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="testing_system.course",
            ),
        ),
    ]
