# Generated by Django 4.2.2 on 2023-07-31 18:02

import django.db.models.deletion
import mentorship.mixins
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mentorship", "0005_create_topic_model"),
        ("testing_system", "0001_create_course_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField()),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="testing_system.course",
                    ),
                ),
                (
                    "image",
                    models.ManyToManyField(blank=True, null=True, to="mentorship.baseimage"),
                ),
            ],
            bases=(models.Model, mentorship.mixins.DateTimeMixin),
        ),
    ]
