# Generated by Django 4.2.2 on 2023-08-06 07:47

import django.db.models.deletion
import mentorship.mixins
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mentorship", "0005_create_topic_model"),
        ("testing_system", "0003_create_article_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnswerType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("radiobutton", "Radiobutton"),
                            ("checkbox", "Checkbox"),
                            ("input", "Input"),
                        ],
                        default="radiobutton",
                        max_length=15,
                    ),
                ),
            ],
            bases=(models.Model, mentorship.mixins.DateTimeMixin),
        ),
        migrations.AddField(
            model_name="article",
            name="teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mentorship.teacher",
            ),
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("is_open", models.BooleanField(default=False)),
                (
                    "time_limit",
                    models.PositiveSmallIntegerField(default=20, verbose_name="Time limit in minutes"),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mentorship.teacher",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="testing_system.topic",
                    ),
                ),
            ],
            bases=(models.Model, mentorship.mixins.DateTimeMixin),
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "test",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="testing_system.test",
                    ),
                ),
            ],
            bases=(models.Model, mentorship.mixins.DateTimeMixin),
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "answer_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="testing_system.answertype",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testing_system.question",
                    ),
                ),
            ],
            bases=(models.Model, mentorship.mixins.DateTimeMixin),
        ),
    ]
